name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x
          include-prerelease: false

      - name: Build
        run: dotnet build -c Release
