name: Generate API Documentation

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Install XMLDoc2Markdown
        run: dotnet tool install -g Nefarius.Tools.XMLDoc2Markdown

      - name: Build
        run: dotnet build -c Release

      - name: Generate API docs
        run: xmldoc2md ./bin/netstandard2.0/${{ github.event.repository.name }}.dll ./docs/

      - name: Check for changes
        id: check-for-changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --exit-code || git commit -m "Update API documentation"
  
      - name: Push changes
        if: success() && steps.check-for-changes.outcome == 'success'
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}