name: Publish Nuget Package

on:
  push:
    tags:
      - v*

jobs:
  test-windows:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: Test Unit and CI suites
        run: >
          dotnet test Tests/Tests.csproj -c Release
          --filter "Category=Unit|Category=CI"
          --logger "trx;LogFileName=test-results.trx"
          --results-directory TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: publish-test-results-windows
          path: TestResults/

  deploy:
    needs: test-windows
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Modify README.md for NuGet
        run: |
          sed -i 's/# <img[^>]*>/# /' README.md

      - name: Build
        run: dotnet build -c Release

      - name: Make Nuget Packages
        run: dotnet pack -c Release

      - name: NuGet login (OIDC)
        id: login
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1
        with:
          user: Nefarius

      - name: Publish To Nuget
        run: dotnet nuget push bin/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
